plugins:
  - [
      "@semantic-release/commit-analyzer",
      {
        "releaseRules": [
          { "type": "chore", "scope": "deps", "release": "patch" },
          { "type": "chore", "scope": "dependencies", "release": "patch" },
          { "type": "chore", "scope": "deps-dev", "release": "patch" },
          { "type": "docs", "scope": "README", "release": "patch" },
          { "type": "refactor", "release": "patch" },
          { "type": "style", "release": "patch" }
        ]
      }
    ]
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - [
      "@semantic-release/exec",
      {
        prepareCmd: "uv version ${nextRelease.version} && npm version ${nextRelease.version} --no-git-tag-version",
      },
    ]
  - [
      "@semantic-release/git",
      {
        message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        assets: ["CHANGELOG.md", "pyproject.toml", "package.json", "uv.lock"],
      },
    ]
  - "@semantic-release/github"

branches:
  - main
