name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Install Hugo
        run: |
          go install github.com/gohugoio/hugo@latest
      - name: Build site
        run: hugo --minify
      - name: Test Docker build
        run: docker build . --file Dockerfile --tag test-build
  otel:
    permissions:
      contents: read # Required. To access the private repository
      actions: read # Required. To read workflow runs
      pull-requests: read # Optional. To read PR labels
      checks: read # Optional. To read run annotations
    if: always()
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Export workflow
        uses: corentinmusard/otel-cicd-action@v4
        with:
          otlpEndpoint: ${{ secrets.OTLP_ENDPOINT }}
          otlpHeaders: ${{ secrets.OTLP_HEADERS }}
          otlpAuthorization: ${{ secrets.OTLP_AUTH_TOKEN }}
          otelToken: ${{ secrets.OTEL_TOKEN }}
