name: Build Docker image

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install hugo
        run: sudo apt-get install hugo -y
      - name: Hugo build
        run: hugo
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag martynvandijke/vandijke.xyz:latest
      - name: Push Docker image
        run: docker push martynvandijke/vandijke.xyz:latest

      - name: Gotify Success Notification
        if: success()
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: ${{ secrets.GOTIFY_API_BASE }}
          gotify_app_token: ${{ secrets.GOTIFY_APP_TOKEN }}
          notification_title: 'Build Successful - vandijke.xyz'
          notification_message: 'Site built and Docker image pushed successfully.'

      - name: Gotify Failure Notification
        if: failure()
        uses: eikendev/gotify-action@master
        with:
          gotify_api_base: ${{ secrets.GOTIFY_API_BASE }}
          gotify_app_token: ${{ secrets.GOTIFY_APP_TOKEN }}
          notification_title: 'Build Failed - vandijke.xyz'
          notification_message: 'The build workflow has failed. ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          notification_priority: 5

